# Generated by Django 3.0.2 on 2020-01-09 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=10)),
                ('original_price', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('is_swapped', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to=settings.AUTH_USER_MODEL)),
                ('swap_requesters', models.ManyToManyField(related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
