# Generated by Django 3.0.2 on 2020-01-09 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes_swap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='swap_requesters',
        ),
        migrations.CreateModel(
            name='SwapRequester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_requesters', to='clothes_swap.Item')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requesters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
